---
name: iris-esmf-regrid
channels:
  - conda-forge
  - nodefaults

dependencies:
  # core dependencies
  - esmpy
  - iris
  # testing dependencies
  - flake8
  - pytest>=3.9,!=6.0.0rc1,!=6.0.0
  - pytest-cov>=2.10.1
  - pytest-env
  - pytest-html!=2.1.0
  - pytest-metadata>=1.5.1
  - pytest-mypy
  - pytest-mock
  - pytest-xdist
